### PR TITLE
fixing path with spaces

### PR DESCRIPTION
**Pull request by yceballost**
I added the possibility to have paths with spaces

For me works, but check the changes, development is not my field :D haha

### CODE REVIEW

**Comment by yceballost** [comment]
wait, clean seem doesn't works

**Comment by yceballost** [comment]
fixed clean too

**Comment by andstor** [comment]
I made some changes to the filtering functionality to ensure proper handling of spaces.

**Comment by andstor** [comment]
Great thank you 🙏

I think we are good to go 🚀

**Pull request merged**
